### PR TITLE
Restrict tweets selector to direct children only

### PR DESCRIPTION
**Pull request by kevinzg**
Fixes the IndexError exception when `tweet.find('.tweet-text')` is empty.
This is an alternative to #33.

### CODE REVIEW

**Comment by timofurrer** [comment]
Please resolve the merge conflicts. Thanks 🎉

**Comment by kevinzg** [comment]
Done

**Comment by ozcanyarimdunya** [comment]
@kevinzg test has been failed, when i tried to run. Have you test it ?

**Comment by kevinzg** [comment]
@ozcanyarimdunya Yes, I ran them. I got `Ran 5 tests in 66.198s`, maybe you had a network error?

**Comment by ozcanyarimdunya** [comment]
ok, thank you.  :+1:

**Pull request merged**
