### PR TITLE
Now able to scrape profiles

### PR DESCRIPTION
**Pull request by NuclearManD**
I needed to be able to scrape information about twitter profiles too, so I added that functionality to your working python code.

My function uses mechanical soup and can pull some basic information:

- location
- birthday
- real/display name
- profile image URL
- bio
- number of tweets
- number of followers
- number following
- number of likes

It could certainly be expanded, but I think it's a useful addition.

### CODE REVIEW

**Comment by kenneth-reitz** [comment]
Many thanks!

**Comment by NuclearManD** [comment]
No problem!  This is the first time I've contributed something like this and It's kindof exciting!

**Comment by NuclearManD** [comment]
Oh yea, just to give credit where credit is due:  I didn't realize commits made after a pull request were submitted would be included in the pull request, so I had added code to my repo from another pull request ([https://github.com/kennethreitz/twitter-scraper/pull/41]), so some of the new code in twitter_scraper.py is from that fork and is not my own.  It's for searching by hashtag.  It seems to be stable, you can contact me or make another comment here if you have any questions.

**Comment by bildzeitung** [comment]
I'm glad the work turned out to be useful :)

**Pull request merged**
